<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Книга выдана</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <h1>Книга выдана</h1>
    <p>Вы успешно взяли книгу: ${book.title}</p>
    <a href="/books" class="btn btn-primary">Вернуться к списку книг</a>
</div>
</body>
</html>
