register_success.ftlh<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация не удалась</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <h1>Регистрация не удалась</h1>
    <p>Пользователь с таким идентификатором уже существует.</p>
    <a href="/register" class="btn btn-primary">Попробовать снова</a>
</div>
</body>
</html>
